package ru.barsopen.plsqlconverter.ast.typed;
public interface standard_function extends table_expression_element, _baseNode {
  // implemented by: standard_function_enabling_over, standard_function_count, standard_function_xmlcast, standard_function_case, standard_function_enabling_within_or_over, standard_function_extract, standard_function_translate, standard_function_trim, standard_function_xmlagg, standard_function_xmlparse, standard_function_root, standard_function_table, standard_function_xmlelement
}
